/**
 * What setup writes into the Lore of a new Space by itself, because the MVP
 * has no guided first session: the Space's own corpus entry, from the form,
 * and the mirror of each repository, with a skeleton generated by the Lore's
 * own generator. Each write also adds the file's line to its folder's index,
 * so that the Lore passes lore-integrity.
 */

import { lstat, readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { type CommandRunner, commandFailure, runSucceeded } from '../exec/runner.js';
import { parseLoreFrontmatter, serializeLoreFrontmatter } from '../frontmatter/index.js';
import { writeFileAtomic } from '../fs/atomic-write.js';
import { SPACE_LAYOUT, spacePaths } from '../layout/space-paths.js';
import { parseLoreIndex } from '../lore/index-file.js';
import { type Failure, type Result, errorCode, errorMessage, fail, ok } from '../result.js';

/** The generator of a repository's skeleton, relative to the Space's folder. */
export const REPOSITORY_SKELETON_GENERATOR = 'lore/mirrors/generators/repository-skeleton.py';

/** A skeleton with more lines than this is stored with the depth limit below. */
export const MIRROR_SKELETON_MAX_LINES = 2000;

/** The `--depth` of a skeleton that would otherwise pass `MIRROR_SKELETON_MAX_LINES`. */
export const MIRROR_SKELETON_DEPTH = 2;

/** How long a generator may run, in milliseconds. */
export const SKELETON_TIMEOUT_MS = 120_000;

/**
 * Why a Lore write failed.
 * `lore-write-failed`: a file could not be read or written.
 * `generator-failed`: `python3` or the generator did not give a skeleton.
 */
export type LoreWriteFailureKind = 'lore-write-failed' | 'generator-failed';

type LoreWriteResult<T> = Result<T, Failure<LoreWriteFailureKind>>;

/** A line a generator prints: a scalar in double quotes with the two escapes `\"` and `\\`. */
const SKELETON_LINE = /^"(?:[^"\\]|\\["\\])*"$/;

async function readText(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8');
  } catch (caught) {
    if (errorCode(caught) === 'ENOENT') return null;
    throw caught;
  }
}

/** Whether the `index.md` of `dir` has a line for the file `fileName`. */
export async function indexListsFile(dir: string, fileName: string): Promise<boolean> {
  const text = await readText(join(dir, 'index.md')).catch(() => null);
  if (text === null) return false;
  return parseLoreIndex(text).lines.some((line) => !line.isFolder && line.name === fileName);
}

/**
 * Add the line of the file `fileName` to the `index.md` of `dir`, at the end.
 * Nothing is written when the index already has a line for it.
 */
export async function addIndexLine(
  dir: string,
  fileName: string,
  sentence: string,
): Promise<LoreWriteResult<void>> {
  const indexPath = join(dir, 'index.md');
  try {
    const text = await readText(indexPath);
    if (text === null) return fail('lore-write-failed', `${indexPath} is missing.`);
    if (await indexListsFile(dir, fileName)) return ok(undefined);
    const line = `- [${fileName}](./${fileName}): ${sentence}`;
    const written = await writeFileAtomic(indexPath, `${text.replace(/\n*$/, '\n')}${line}\n`);
    return written.ok ? ok(undefined) : fail('lore-write-failed', written.error.message);
  } catch (caught) {
    return fail('lore-write-failed', `${indexPath} cannot be read: ${errorMessage(caught)}`);
  }
}

/** The file name of a corpus entry: its term in lower case, as the corpus entry "card" says. */
export function corpusEntryFileName(term: string): string {
  return `${term.toLowerCase()}.md`;
}

/**
 * The corpus entry of the template that already has the file name the Space's
 * own entry would get, as a path relative to the template, or `null`. Names
 * are compared without regard to case.
 */
export async function templateCorpusEntryNamed(
  templateDir: string,
  spaceName: string,
): Promise<string | null> {
  const wanted = corpusEntryFileName(spaceName);
  for (const layer of ['core', 'default']) {
    const dir = join(templateDir, SPACE_LAYOUT.lore, 'corpus', layer);
    const names = await readdir(dir).catch(() => [] as string[]);
    const hit = names.find((name) => name.toLowerCase() === wanted);
    if (hit !== undefined) return `${SPACE_LAYOUT.lore}/corpus/${layer}/${hit}`;
  }
  return null;
}

/** The description as it is placed in the card: line ends made one kind, and no text that reads as a link. */
function descriptionForCard(description: string): string {
  const text = description.replace(/\r\n?/g, '\n').trim().replace(/\]\(/g, '] (');
  return text === '' ? 'The Human Lead gave no description of this Space at setup.' : text;
}

/** What `writeSpaceCorpusEntry` needs. */
export type SpaceCorpusEntryInput = {
  spaceRoot: string;
  /** The Space's name, which is the entry's term. */
  name: string;
  /** The Human Lead's words from the form. */
  description: string;
  /** The Space repository, as `owner/name`. */
  repository: string;
};

function corpusDir(spaceRoot: string): string {
  return join(spacePaths(spaceRoot).lore, 'corpus');
}

/** Whether the Space's own corpus entry is there and listed in the corpus index. */
export async function hasSpaceCorpusEntry(spaceRoot: string, name: string): Promise<boolean> {
  const fileName = corpusEntryFileName(name);
  const info = await lstat(join(corpusDir(spaceRoot), fileName)).catch(() => null);
  return info?.isFile() === true && (await indexListsFile(corpusDir(spaceRoot), fileName));
}

/**
 * Write the Space's own corpus entry, `lore/corpus/<name>.md`, and its line in
 * `lore/corpus/index.md`. An entry that is already there is kept as it is.
 */
export async function writeSpaceCorpusEntry(
  input: SpaceCorpusEntryInput,
): Promise<LoreWriteResult<void>> {
  const fileName = corpusEntryFileName(input.name);
  const path = join(corpusDir(input.spaceRoot), fileName);
  const frontmatter = serializeLoreFrontmatter({
    type: 'corpus',
    term: input.name,
    points_at: [SPACE_LAYOUT.manifest],
  });
  if (!frontmatter.ok) return fail('lore-write-failed', frontmatter.error.message);
  if ((await lstat(path).catch(() => null)) === null) {
    const text = [
      '---',
      frontmatter.value,
      '---',
      '',
      `# ${input.name}`,
      '',
      '## What it means',
      '',
      `${input.name} is the name of this Space. The Human Lead described it at setup in these words:`,
      '',
      descriptionForCard(input.description),
      '',
      '## Where it is kept',
      '',
      `The Space is the repository \`${input.repository}\` on GitHub, and the folder of its clone on each desk. The file \`${SPACE_LAYOUT.manifest}\` names its repository, its Project and its payloads.`,
      '',
      '## What acts on it',
      '',
      'The companion wrote this entry at setup, from the form the Human Lead filled in. With the Lore claimed, the Human Lead and the sessions edit it as any other card of the Space.',
      '',
    ].join('\n');
    const written = await writeFileAtomic(path, text);
    if (!written.ok) return fail('lore-write-failed', written.error.message);
  }
  return addIndexLine(
    corpusDir(input.spaceRoot),
    fileName,
    'the entry for this Space, with the description the Human Lead gave at setup.',
  );
}

/** What `writeRepositoryMirror` needs. */
export type RepositoryMirrorInput = {
  spaceRoot: string;
  /** Runs `python3`. */
  runner: CommandRunner;
  /** The repository's name in the Space; its checkout is `repos/<name>`. */
  name: string;
  /** The repository on GitHub, as `owner/name`. */
  github: string;
};

function mirrorsDir(spaceRoot: string): string {
  return join(spacePaths(spaceRoot).lore, 'mirrors');
}

/** Whether the mirror of the repository `name` is there and listed in the mirrors' index. */
export async function hasRepositoryMirror(spaceRoot: string, name: string): Promise<boolean> {
  const fileName = `${name}.md`;
  const info = await lstat(join(mirrorsDir(spaceRoot), fileName)).catch(() => null);
  return info?.isFile() === true && (await indexListsFile(mirrorsDir(spaceRoot), fileName));
}

/**
 * Run the Space's generator for repositories on `repos/<name>`, from the
 * Space's folder, and return the lines it printed. `depth` adds `--depth`.
 */
export async function generateRepositorySkeleton(
  input: Pick<RepositoryMirrorInput, 'spaceRoot' | 'runner' | 'name'>,
  depth: number | null = null,
): Promise<LoreWriteResult<string[]>> {
  const script = join(input.spaceRoot, ...REPOSITORY_SKELETON_GENERATOR.split('/'));
  const args = [script, `${SPACE_LAYOUT.repos}/${input.name}`];
  if (depth !== null) args.push('--depth', String(depth));
  const run = await input.runner.run('python3', args, {
    cwd: input.spaceRoot,
    timeoutMs: SKELETON_TIMEOUT_MS,
  });
  if (!runSucceeded(run)) {
    return fail(
      'generator-failed',
      `The skeleton of the repository ${input.name} was not generated: ${commandFailure('python3', args.slice(1), run).message}`,
    );
  }
  const lines = run.stdout.split('\n').filter((line) => line !== '');
  const odd = lines.find((line) => !SKELETON_LINE.test(line));
  if (odd !== undefined) {
    return fail(
      'generator-failed',
      `The generator printed a line that is not a path in double quotes: ${odd}`,
    );
  }
  return ok(lines);
}

/**
 * Write the mirror of the repository `name`, `lore/mirrors/<name>.md`, with a
 * first skeleton and no description, and its line in `lore/mirrors/index.md`.
 * A mirror that is already there is kept as it is.
 */
export async function writeRepositoryMirror(
  input: RepositoryMirrorInput,
): Promise<LoreWriteResult<void>> {
  const fileName = `${input.name}.md`;
  const path = join(mirrorsDir(input.spaceRoot), fileName);
  if ((await lstat(path).catch(() => null)) === null) {
    let depth: number | null = null;
    let skeleton = await generateRepositorySkeleton(input);
    if (skeleton.ok && skeleton.value.length > MIRROR_SKELETON_MAX_LINES) {
      depth = MIRROR_SKELETON_DEPTH;
      skeleton = await generateRepositorySkeleton(input, depth);
    }
    if (!skeleton.ok) return skeleton;

    const head = serializeLoreFrontmatter({
      type: 'mirror',
      payload: input.name,
      generator: REPOSITORY_SKELETON_GENERATOR,
    });
    if (!head.ok) return fail('lore-write-failed', head.error.message);
    // The items are written as the generator printed them, as the index of the generators says.
    const stored =
      skeleton.value.length === 0
        ? ['skeleton: []']
        : ['skeleton:', ...skeleton.value.map((line) => `  - ${line}`)];
    const command = `python3 ${REPOSITORY_SKELETON_GENERATOR} ${SPACE_LAYOUT.repos}/${input.name}${
      depth === null ? '' : ` --depth ${depth}`
    }`;
    const depthSentence =
      depth === null
        ? 'The stored skeleton was generated without the option `--depth`, so it lists every file of the default branch.'
        : `The whole listing has more than ${MIRROR_SKELETON_MAX_LINES} lines, so the stored skeleton was generated with \`--depth ${depth}\` and is compared only with a skeleton generated with the same value.`;
    const text = [
      '---',
      head.value,
      ...stored,
      '---',
      '',
      `# The repository \`${input.name}\``,
      '',
      `This mirror describes the repository \`${input.name}\` of the Space, which is \`${input.github}\` on GitHub. Its checkout on a desk is the folder \`${SPACE_LAYOUT.repos}/${input.name}/\`.`,
      '',
      'Read this mirror before you write to the repository.',
      '',
      '## What the repository holds',
      '',
      'The companion wrote this mirror at setup with a first skeleton and no description. What the repository holds, and where things go in it, is written here by the Human Lead and the sessions.',
      '',
      '## The skeleton',
      '',
      "The skeleton of this mirror is the listing of the repository's default branch. The generator for repositories prints it when it is run from the Space's folder:",
      '',
      '```',
      command,
      '```',
      '',
      depthSentence,
      '',
    ].join('\n');
    const parsed = parseLoreFrontmatter(text);
    if (!parsed.ok) {
      return fail(
        'lore-write-failed',
        `The mirror of ${input.name} was not written, because its frontmatter does not read back: ${parsed.error.message}`,
      );
    }
    const written = await writeFileAtomic(path, text);
    if (!written.ok) return fail('lore-write-failed', written.error.message);
  }
  return addIndexLine(
    mirrorsDir(input.spaceRoot),
    fileName,
    `the mirror of the repository \`${input.name}\`, whose checkout is \`${SPACE_LAYOUT.repos}/${input.name}/\`.`,
  );
}
