/**
 * Migration from v0.8 (stage M6): the plan, the thirteen steps, the ledger.
 *
 * Phase M6.2 owns this file, `types.ts`, `context.ts`, `targets.ts`,
 * `ledger.ts`, `checks.ts` and `plan.ts`. The step files under `steps/` are
 * filled by the phases that build their `run`: M6.3 steps 1 to 10 and 12,
 * M6.4 step 11, M6.6 step 13 (with `verify.ts`). Their exports are listed
 * here already, so those phases do not edit this file.
 */

export {
  MIGRATION_DEFAULT_FOCUS_STAGE,
  MIGRATION_MAPPING_ROWS,
  MIGRATION_STEP_IDS,
  type MigrationFailure,
  type MigrationFailureKind,
  type MigrationField,
  type MigrationFieldId,
  type MigrationFocusStage,
  type MigrationForm,
  type MigrationInput,
  type MigrationIssueKind,
  type MigrationIssuePlan,
  type MigrationLedgerRecord,
  type MigrationMappingItem,
  type MigrationMappingRow,
  type MigrationMappingRowId,
  type MigrationNotCarried,
  type MigrationPlan,
  type MigrationPlannedStep,
  type MigrationRefusal,
  type MigrationRefusalKind,
  type MigrationReport,
  type MigrationRepositoryState,
  type MigrationSourceRepository,
  type MigrationStepId,
  type MigrationWarning,
  type MigrationWarningKind,
} from './types.js';
export type {
  MigrationContext,
  MigrationDeps,
  MigrationSettings,
  MigrationStep,
} from './context.js';
export {
  ARCHIVE_DIR as MIGRATION_ARCHIVE_DIR,
  ARCHIVE_POINTER as MIGRATION_ARCHIVE_POINTER,
  type ArchivedFile as MigrationArchivedFile,
  type ContractCard as MigrationContractCard,
  type DraftFile as MigrationDraftFile,
  MIGRATED_MARKER_NAME,
  type MigrationTargets,
  archivedPath as migrationArchivedPath,
  contractCardName as migrationContractCardName,
  migrationIssues,
  migrationTargets,
} from './targets.js';
export {
  MIGRATION_LEDGER_FILE,
  type MigrationLedgerEntry,
  appendMigrationLedger,
  isMigrationLedgerRecord,
  readMigrationLedger,
} from './ledger.js';
export { STEP_NOT_BUILT as MIGRATION_STEP_NOT_BUILT } from './checks.js';
export {
  type PreparedMigration,
  migrationSteps,
  planMigration,
  prepareMigration,
  runMigration,
} from './plan.js';
