/**
 * The life of a session on the desk: it starts in Read only, enters Writing
 * with the targets it was granted, leaves Writing, and ends. Phase M4.2.
 *
 * Each function takes a decision of the claim rules (`space/claims`) and
 * applies it through the functions of `sessions.ts` and `claims.ts`.
 *
 * A session's mode is in `sessions.json` and its claims are in `claims.json`,
 * so a step that changes both is two atomic writes, and the order is chosen so
 * that what is on disk between them lets a session write less, never more:
 *
 * - Entering Writing writes the claims first and the mode second.
 * - Leaving Writing and ending a session write the mode first and release the
 *   claims second.
 *
 * In both orders the state between the two writes is the same: the session is
 * in Read only and the claims are recorded. The `write-guard` check refuses
 * the Lore and every payload to that session, because it reads the mode first,
 * and another session is refused the targets, because they are held. A session
 * in Writing without a claim is never on disk.
 *
 * Both writes happen inside one synchronous function, so nothing else in the
 * process sees that state. The check script, which is another process, can,
 * and so can the next start of the app when the app stopped between the two
 * writes. `repairSessionRecords` brings such a desk back to the rule: it
 * releases the claims of a session that is not in Writing, and puts a session
 * that is in Writing with no claim in Read only. `enterWriting` runs it before
 * it decides, so a claim left by a stopped step does not hold a target.
 *
 * When the second write fails while the process keeps running, `enterWriting`
 * releases the claims it wrote. The other two steps leave the claims for the
 * repair: putting the session back in Writing would let it write more.
 *
 * Session closes. A session close is the commit a session left on a root when
 * it left Writing (architecture document, sections 3.5 and 5.6). Leaving
 * Writing and ending a session record one for each entry of the option
 * `closes`, when the session was in Writing at the call. They are appended
 * after the mode is written and before the claims are released, so a close is
 * on disk only for a session that has left Writing. A step stopped after the
 * mode write records no close; the baseline points then group that session's
 * commits by its start and end times. A close that cannot be written does not
 * keep the claims: they are released, and the failure is in `closeFailure`.
 *
 * This file reads no repository. The caller reads the present commit of each
 * root the session holds before it calls, with `readSessionCloseCommits` of
 * `space/baseline`, and passes what that gave.
 */

import { decideLeaveWriting, decideWritingRequest, heldReason, refusal } from '../claims/rules.js';
import type {
  ClaimablePayloads,
  WritingGrant,
  WritingRefusal,
  WritingRequest,
} from '../claims/types.js';
import { type Result, err, ok } from '../result.js';
import { addClaims, listClaims, releaseClaim, releaseClaims } from './claims.js';
import type { Desk, DeskFailure } from './desk.js';
import { isJsonObject, isSessionRecord } from './guards.js';
import { recordSessionClose } from './root-commits.js';
import { addSession, closeSession, listSessions, updateSession } from './sessions.js';
import { type DeskRecordFile, readDeskRecords } from './store.js';
import type {
  Claim,
  IssueRef,
  JsonObject,
  SessionClose,
  SessionProfile,
  SessionPurpose,
  SessionRecord,
  SessionSpend,
} from './types.js';

/** What the caller gives to start a session; the desk adds the mode and the time. */
export type SessionStart = {
  /** Generated by the companion when the AI tab starts its engine. */
  id: string;
  /** An id from the engines registry. */
  engine: string;
  /** The item or focus the session is on, when it is on one. */
  item?: IssueRef;
  /** The options that changed the guard, by name. Written only when non-empty. */
  unguarded?: string[];
  /** The profile the session ran, as it was when the session started. */
  profile?: SessionProfile;
  /** The texts of the parameters ticked at the start, in order. Written only when non-empty. */
  params?: readonly string[];
  /** The automatically started PM session. Absent is the normal Human Lead session. */
  purpose?: SessionPurpose;
};

/** What `repairSessionRecords` changed. Both lists are empty on a desk that follows the rule. */
export type SessionRepair = {
  /** The claims that were released because their session is not in Writing. */
  released: Claim[];
  /** The ids of the sessions that were in Writing with no claim and are in Read only now. */
  returnedToReadOnly: string[];
};

/** A session that entered Writing, or that holds more targets than before. */
export type WritingEntered = {
  session: SessionRecord;
  /** The claims this step wrote. */
  claims: Claim[];
  grant: WritingGrant;
  repaired: SessionRepair;
};

/** The present commit of a root a session holds, read by the caller before the session leaves Writing. */
export type SessionCloseCommit = { rootId: string; commit: string };

/** A session that left Writing, or that ended, and the claims that were released. */
export type WritingLeft = {
  session: SessionRecord;
  released: Claim[];
  /** The session closes this step recorded. Empty when none was passed or the session was not in Writing. */
  closes: SessionClose[];
  /** Set when a session close could not be written. The closes before it are in `closes`; the claims were released all the same. */
  closeFailure?: DeskFailure;
};

/** Options of leaving Writing and of ending a session. */
export type LeaveOptions = Pick<LifecycleOptions, 'betweenWrites'> & {
  /**
   * The present commit of each root the session holds. One session close is
   * recorded for each, when the session is in Writing at the call.
   */
  closes?: readonly SessionCloseCommit[];
};

/** Options of ending a session: `LeaveOptions` and what it spent. */
export type EndOptions = LeaveOptions & {
  /** What the session spent, recorded on the same write that closes it. */
  spend?: SessionSpend;
};

/** Options of the steps that make two writes. */
export type LifecycleOptions = {
  /** The item the session is on, recorded with the mode when the session enters Writing. */
  item?: IssueRef;
  /**
   * Called after the first write and before the second. For a test that stops
   * a step halfway or looks at the desk between the writes; the app does not pass it.
   * It must not write the desk: a repair run from here releases the claims that the
   * step has just written, and the step then puts the session in Writing without them.
   */
  betweenWrites?: () => void;
};

/** Every entry of `sessions.json` that has an id, understood by this build or not. */
const SESSION_ENTRIES: DeskRecordFile<JsonObject> = {
  name: 'sessions',
  guard: (value: unknown): value is JsonObject =>
    isJsonObject(value) && typeof value.id === 'string',
};

function withNote<E extends { message: string }>(error: E, note: string): E {
  return { ...error, message: `${error.message} ${note}` };
}

/**
 * Record a new session. A session starts in Read only and holds no target.
 * Fails with `duplicate` when the id is already recorded.
 */
export function startSession(desk: Desk, start: SessionStart): Result<SessionRecord, DeskFailure> {
  return addSession(desk, {
    id: start.id,
    engine: start.engine,
    attended: true,
    mode: 'read-only',
    startedAt: desk.now().toISOString(),
    ...(start.item !== undefined ? { item: start.item } : {}),
    ...(start.unguarded !== undefined && start.unguarded.length > 0
      ? { unguarded: start.unguarded }
      : {}),
    ...(start.profile !== undefined ? { profile: start.profile } : {}),
    ...(start.params !== undefined && start.params.length > 0 ? { params: [...start.params] } : {}),
    ...(start.purpose !== undefined ? { purpose: start.purpose } : {}),
  });
}

/**
 * Bring the two records back to the rule that a claim belongs to a session in
 * Writing and a session in Writing holds a claim. The claims of a session that
 * is in Read only, has ended, or has no entry in `sessions.json` are released.
 * A session in Writing with no claim is put in Read only. The claims of a
 * session whose entry this build does not understand are left as they are:
 * another build of the companion wrote it, and this one cannot tell its mode.
 *
 * The app calls it when it opens a desk. Nothing is written on a desk that
 * follows the rule.
 */
export function repairSessionRecords(desk: Desk): Result<SessionRepair, DeskFailure> {
  const entries = readDeskRecords(desk, SESSION_ENTRIES);
  if (!entries.ok) return entries;
  const claims = listClaims(desk);
  if (!claims.ok) return claims;

  const released: Claim[] = [];
  // The sessions whose claims this repair released. A released claim is known by its
  // session and not by the object: `releaseClaims` reads the file again and returns other objects.
  const releasedFor = new Set<string>();
  for (const sessionId of new Set(claims.value.map((claim) => claim.sessionId))) {
    const own = entries.value.filter((entry) => entry.id === sessionId);
    if (own.some((entry) => !isSessionRecord(entry))) continue;
    const writing = own.some(
      (entry) => isSessionRecord(entry) && entry.mode === 'writing' && entry.closedAt === undefined,
    );
    if (writing) continue;
    const gone = releaseClaims(desk, sessionId);
    if (!gone.ok) return gone;
    released.push(...gone.value);
    releasedFor.add(sessionId);
  }

  const returnedToReadOnly: string[] = [];
  for (const entry of entries.value) {
    if (!isSessionRecord(entry) || entry.mode !== 'writing') continue;
    // A session that ended and was left in Writing had its claims released above, so it holds nothing now.
    const holds =
      !releasedFor.has(entry.id) && claims.value.some((claim) => claim.sessionId === entry.id);
    if (holds) continue;
    const changed = updateSession(desk, entry.id, { mode: 'read-only' });
    if (!changed.ok) return changed;
    returnedToReadOnly.push(entry.id);
  }
  return ok({ released, returnedToReadOnly });
}

/**
 * Apply a request to enter Writing that the Human Lead confirmed: decide it
 * against the desk as it is now, write the claims, then put the session in
 * Writing. A refused request writes nothing. A session that is in Writing
 * already gets the new targets beside those it holds.
 *
 * The claims are written first. When the mode cannot be written after them,
 * the claims are released again and the failure is returned.
 */
export function enterWriting(
  desk: Desk,
  manifest: ClaimablePayloads,
  request: WritingRequest,
  options: LifecycleOptions = {},
): Result<WritingEntered, DeskFailure | WritingRefusal> {
  const repaired = repairSessionRecords(desk);
  if (!repaired.ok) return repaired;
  const sessions = listSessions(desk);
  if (!sessions.ok) return sessions;
  const claims = listClaims(desk);
  if (!claims.ok) return claims;
  const grant = decideWritingRequest(
    { manifest, sessions: sessions.value, claims: claims.value },
    request,
  );
  if (!grant.ok) return grant;

  const added = addClaims(desk, request.sessionId, grant.value.targets);
  if (!added.ok) {
    const error = added.error;
    if (error.kind !== 'held') return err(error);
    return err(refusal(error.held.map((holder) => heldReason(holder.target, holder))));
  }

  options.betweenWrites?.();

  const session = updateSession(desk, request.sessionId, {
    mode: grant.value.mode,
    ...(options.item !== undefined ? { item: options.item } : {}),
  });
  if (!session.ok) {
    const undone = added.value.every(
      (claim) => releaseClaim(desk, request.sessionId, claim.target).ok,
    );
    return err(
      withNote(
        session.error,
        undone
          ? "The session's mode was not changed, and the claims that were written for it were released again."
          : "The session's mode was not changed. The claims that were written for it could not be released; they are released when the desk's session records are repaired.",
      ),
    );
  }
  return ok({
    session: session.value,
    claims: added.value,
    grant: grant.value,
    repaired: repaired.value,
  });
}

/**
 * Return a session to Read only and release every target it holds: the header's
 * Leave Writing action and the tool `leave_writing`. The mode is written first
 * and the claims are released second. A session that is in Read only already
 * keeps its mode, and whatever it still holds is released. Between the two a
 * session close is recorded for each entry of `options.closes`.
 */
export function leaveWriting(
  desk: Desk,
  sessionId: string,
  options: LeaveOptions = {},
): Result<WritingLeft, DeskFailure | WritingRefusal> {
  return leave(desk, sessionId, options, (session) =>
    session.mode === 'writing'
      ? updateSession(desk, sessionId, { mode: 'read-only' })
      : ok(session),
  );
}

/**
 * Record that a session ended: its close time is set, it is in Read only, and
 * every target it holds is released. When `options.spend` is given it is
 * written in the same call that sets the close time. The record is written
 * first and the claims are released second. A session that ended before keeps
 * its close time and its spend.
 */
export function endSession(
  desk: Desk,
  sessionId: string,
  options: EndOptions = {},
): Result<WritingLeft, DeskFailure | WritingRefusal> {
  return leave(desk, sessionId, options, (session) =>
    session.closedAt === undefined ? closeSession(desk, sessionId, options.spend) : ok(session),
  );
}

function leave(
  desk: Desk,
  sessionId: string,
  options: LeaveOptions,
  writeSession: (session: SessionRecord) => Result<SessionRecord, DeskFailure>,
): Result<WritingLeft, DeskFailure | WritingRefusal> {
  const sessions = listSessions(desk);
  if (!sessions.ok) return sessions;
  const claims = listClaims(desk);
  if (!claims.ok) return claims;
  const decision = decideLeaveWriting(
    { sessions: sessions.value, claims: claims.value },
    sessionId,
  );
  if (!decision.ok) return decision;
  const current = sessions.value.find((session) => session.id === sessionId);
  // The decision refuses a session the desk has no record of, so this one has a record.
  if (current === undefined) return err(missing(sessionId));

  const wasWriting = current.mode === 'writing' && current.closedAt === undefined;

  const session = writeSession(current);
  if (!session.ok) return session;

  // The session has left Writing on disk, so a close recorded now is true. See this file's header.
  const closes: SessionClose[] = [];
  let closeFailure: DeskFailure | undefined;
  if (wasWriting) {
    for (const close of options.closes ?? []) {
      const recorded = recordSessionClose(desk, {
        rootId: close.rootId,
        commit: close.commit,
        sessionId,
      });
      if (!recorded.ok) {
        closeFailure = recorded.error;
        break;
      }
      closes.push(recorded.value);
    }
  }

  options.betweenWrites?.();

  const released = releaseClaims(desk, sessionId);
  if (!released.ok) {
    return err(
      withNote(
        released.error,
        "The session is in Read only. The claims it held could not be released; they are released when the desk's session records are repaired.",
      ),
    );
  }
  return ok({
    session: session.value,
    released: released.value,
    closes,
    ...(closeFailure !== undefined ? { closeFailure } : {}),
  });
}

function missing(sessionId: string): DeskFailure {
  return { kind: 'not-found', message: `no session "${sessionId}" is recorded` };
}
