/**
 * The shapes of the desk's records.
 *
 * This file imports nothing, so the renderer can take every type here with
 * `import type`. Each record type is what one of the desk's JSON files holds in
 * its `records` list; every file has the form `{ "version": 1, "records": [...] }`.
 *
 * `sessions.json` and `claims.json` are read by the `write-guard` check script
 * of the Lore (`contracts/core/write-guard.py`). The fields it reads are the
 * `id` and `mode` of a session, and the `sessionId` and `target` (`kind`,
 * `name`, `branch`) of a claim. Changing one of them means changing the script.
 */

/** A JSON value, as `JSON.parse` returns it. */
export type JsonValue = string | number | boolean | null | JsonValue[] | JsonObject;

/** A JSON object. */
export type JsonObject = { [key: string]: JsonValue };

/** The two modes of a session. */
export type SessionMode = 'read-only' | 'writing';

/**
 * What a session in Writing may write: the Lore, a publish area, or a
 * repository held whole on a named branch.
 */
export type WriteTarget =
  | { kind: 'lore' }
  | { kind: 'publish-area'; name: string }
  | { kind: 'repository'; name: string; branch: string };

/** An issue on GitHub. */
export type IssueRef = { repository: string; number: number; url: string };

/** One session of an AI tab. Kept in `sessions.json`. */
export type SessionRecord = {
  /** Generated by the companion when the AI tab starts its engine. */
  id: string;
  /** An id from the engines registry. */
  engine: string;
  /** Always `true` in the MVP: unattended sessions are a non-goal. */
  attended: true;
  mode: SessionMode;
  /** ISO 8601. */
  startedAt: string;
  /** ISO 8601, present once the session has ended. */
  closedAt?: string;
  /** The item or focus the session is on, when it is on one. */
  item?: IssueRef;
  /** The session's own issue, created when it first enters Writing. */
  issue?: IssueRef;
  /** The options that changed the guard when the session started. Absent when none. */
  unguarded?: string[];
};

/** The fields of a session that change after it starts. */
export type SessionPatch = {
  mode?: SessionMode;
  closedAt?: string;
  item?: IssueRef;
  issue?: IssueRef;
};

/** A write target held by a session. Kept in `claims.json`. */
export type Claim = { sessionId: string; target: WriteTarget; claimedAt: string };

/**
 * Why `addClaims` wrote nothing: another session holds a target that was asked
 * for. `held` is the claim of each holder, and `message` names each of them.
 */
export type ClaimsHeldFailure = { kind: 'held'; message: string; held: Claim[] };

/** The three answers the Human Lead can give at a gate. */
export type GateAnswerValue = 'yes' | 'no' | 'take-over';

/** The Human Lead's answer at a gate of a process. Kept in `gate-answers.json`. */
export type GateAnswer = {
  id: string;
  sessionId: string;
  process: string;
  step: string;
  question: string;
  answer: GateAnswerValue;
  /** ISO 8601. */
  answeredAt: string;
};

/** What the caller gives to record a gate answer; the desk adds `id` and `answeredAt`. */
export type GateAnswerInput = Omit<GateAnswer, 'id' | 'answeredAt'>;

/** An item tagged for unattended work. Defined for the record; nothing in the MVP writes one. */
export type UnattendedTag = { item: IssueRef; taggedAt: string };

/** The Human Lead marked a root as reviewed at `commit`. Kept in `reviewed-marks.json`. */
export type ReviewedMark = { rootId: string; commit: string; markedAt: string };

/** The commit a session left on a root when it left Writing. Kept in `session-closes.json`. */
export type SessionClose = { rootId: string; commit: string; sessionId: string; at: string };

/** The commit a root had the first time the companion saw it. Kept in `first-seen.json`. */
export type FirstSeen = { rootId: string; commit: string; at: string };

/** The app instance that opened a desk for writing. Kept in `owner.json`. */
export type DeskOwner = {
  /** The process id of the instance. */
  pid: number;
  /** When that process started, ISO 8601. Tells two processes with one pid apart. */
  startedAt: string;
  /** When the instance took the desk, ISO 8601. */
  openedAt: string;
};

/** The part of a `DeskOwner` that names a process. */
export type DeskInstance = { pid: number; startedAt: string };

/**
 * Something about the desk's files that the Space window's header shows.
 *
 * - `corrupt-file`: `file` could not be parsed. It was renamed to `setAsideAs`
 *   (`null` when the desk is not writable or the rename failed) and is treated as empty.
 * - `records-not-understood`: `count` entries of `file` do not have the shape
 *   this build knows. They are not used, and they are kept when the file is written.
 * - `stale-owner-replaced`: the owner file named a process that no longer runs.
 */
export type DeskNotice =
  | { kind: 'corrupt-file'; file: string; setAsideAs: string | null; at: string; message: string }
  | { kind: 'records-not-understood'; file: string; count: number; message: string }
  | { kind: 'stale-owner-replaced'; file: string; previous: DeskOwner; message: string };

/**
 * Why a desk operation failed.
 *
 * - `read-failed`, `write-failed`: the filesystem refused.
 * - `newer-version`: the file's `version` is higher than this build writes; it is left as it is.
 * - `not-writable`: another running instance owns the desk, so this one does not write.
 * - `not-owner`: the owner file no longer names this instance.
 * - `invalid-record`: the value to be written does not have the record's shape.
 * - `duplicate`: a record with the same identity is already there.
 * - `not-found`: the record to change is not there.
 */
export type DeskFailureKind =
  | 'read-failed'
  | 'write-failed'
  | 'newer-version'
  | 'not-writable'
  | 'not-owner'
  | 'invalid-record'
  | 'duplicate'
  | 'not-found';
