/**
 * The shapes of the desk's records.
 *
 * This file imports nothing, so the renderer can take every type here with
 * `import type`. Each record type is what one of the desk's JSON files holds in
 * its `records` list; every file has the form `{ "version": 1, "records": [...] }`.
 *
 * `sessions.json` and `claims.json` are read by the `write-guard` check script
 * of the Lore (`contracts/core/write-guard.py`). The fields it reads are the
 * `id` and `mode` of a session, and the `sessionId` and `target` (`kind`,
 * `name`, `branch`) of a claim. Changing one of them means changing the script.
 */

/** A JSON value, as `JSON.parse` returns it. */
export type JsonValue = string | number | boolean | null | JsonValue[] | JsonObject;

/** A JSON object. */
export type JsonObject = { [key: string]: JsonValue };

/** The two modes of a session. */
export type SessionMode = 'read-only' | 'writing';

/** Why the companion started a session. Absent records are ordinary Human Lead sessions. */
export type SessionPurpose = 'pm' | 'dashboard-refresh';

/**
 * What a session in Writing may write: the Lore, a publish area, or a
 * repository held whole on a named branch.
 */
export type WriteTarget =
  | { kind: 'lore' }
  | { kind: 'publish-area'; name: string }
  | { kind: 'repository'; name: string; branch: string };

/** An issue on GitHub. */
export type IssueRef = { repository: string; number: number; url: string };

/**
 * The profile a session ran under, as it was when the session started. Kept on
 * the session record beside `engine` (M14.2). `engine` here names the engine
 * the profile runs, and is a plain `string` and not a catalog id type: this
 * file imports nothing, so the renderer can `import type` from it.
 */
export type SessionProfile = {
  /** The profile's id. The same string as the record's `engine`. */
  id: string;
  /** The profile's name when the session started. */
  name: string;
  /** Which engine the profile runs: a catalog id, or the binary's file name. */
  engine: string;
  /** The model the profile names. Absent when it names none. */
  model?: string;
};

/** What a session spent, written when it ends (M14.2). */
export type SessionSpend = {
  /**
   * Where the numbers come from.
   * - `engine`: the engine reported them and the companion read them.
   * - `none`: the engine reported nothing this build can read. No number follows.
   */
  source: 'engine' | 'none';
  /** The cost in US dollars, when the engine reported one. */
  usd?: number;
  /** The tokens the engine reported. A field is absent when the engine did not report it. */
  tokens?: { input?: number; output?: number; cacheRead?: number; cacheWrite?: number };
  /** The model the engine reported it ran, when it reported one. It can differ from the profile's. */
  model?: string;
};

/** One session of an AI tab. Kept in `sessions.json`. */
export type SessionRecord = {
  /** Generated by the companion when the AI tab starts its engine. */
  id: string;
  /**
   * The id of the profile the session ran. Before M14 the id of the engine it
   * ran; the same string, so no record written before M14 changes meaning.
   */
  engine: string;
  /** Always `true` in the MVP: unattended sessions are a non-goal. */
  attended: true;
  /** Present only for the Space's automatically started Project Manager session. */
  purpose?: SessionPurpose;
  mode: SessionMode;
  /** ISO 8601. */
  startedAt: string;
  /** ISO 8601, present once the session has ended. */
  closedAt?: string;
  /** The item or focus the session is on, when it is on one. */
  item?: IssueRef;
  /**
   * The session's own issue. Created when the session starts, in Read only,
   * and not when it first writes: a session that only reads can restructure
   * the whole plan, and one did — 38 issues created and 37 closed in Read
   * only, with nothing on the board to say who had done it.
   */
  issue?: IssueRef;
  /**
   * Every ticket the session has done substantive work on, in the order it
   * first touched them. `item` is where the session was pointed; this is where
   * it went. A session issue used to carry one `Item:` line, and a session
   * that touched six tickets had nowhere to say so.
   */
  tickets?: IssueRef[];
  /** The options that changed the guard when the session started. Absent when none. */
  unguarded?: string[];
  /** The profile the session ran. Absent on a record written before M14. */
  profile?: SessionProfile;
  /** The texts of the parameters ticked at the start, in order. Absent when none were. */
  params?: string[];
  /** What the session spent, written when it ends. Absent on a record written before M14. */
  spend?: SessionSpend;
};

/** The fields of a session that change after it starts. */
export type SessionPatch = {
  mode?: SessionMode;
  closedAt?: string;
  item?: IssueRef;
  issue?: IssueRef;
  /** Replaces the list whole: the board holds the order and appends to it. */
  tickets?: IssueRef[];
  spend?: SessionSpend;
};

/** A write target held by a session. Kept in `claims.json`. */
export type Claim = { sessionId: string; target: WriteTarget; claimedAt: string };

/**
 * Why `addClaims` wrote nothing: another session holds a target that was asked
 * for. `held` is the claim of each holder, and `message` names each of them.
 */
export type ClaimsHeldFailure = { kind: 'held'; message: string; held: Claim[] };

/** The three answers the Human Lead can give at a gate. */
export type GateAnswerValue = 'yes' | 'no' | 'take-over';

/** The Human Lead's answer at a gate of a process. Kept in `gate-answers.json`. */
export type GateAnswer = {
  id: string;
  sessionId: string;
  process: string;
  step: string;
  question: string;
  answer: GateAnswerValue;
  /** ISO 8601. */
  answeredAt: string;
};

/** What the caller gives to record a gate answer; the desk adds `id` and `answeredAt`. */
export type GateAnswerInput = Omit<GateAnswer, 'id' | 'answeredAt'>;

/** An item tagged for unattended work. Defined for the record; nothing in the MVP writes one. */
export type UnattendedTag = { item: IssueRef; taggedAt: string };

/** The Human Lead marked a root as reviewed at `commit`. Kept in `reviewed-marks.json`. */
export type ReviewedMark = { rootId: string; commit: string; markedAt: string };

/** The commit a session left on a root when it left Writing. Kept in `session-closes.json`. */
export type SessionClose = { rootId: string; commit: string; sessionId: string; at: string };

/** The commit a root had the first time the companion saw it. Kept in `first-seen.json`. */
export type FirstSeen = { rootId: string; commit: string; at: string };

/** The app instance that opened a desk for writing. Kept in `owner.json`. */
export type DeskOwner = {
  /** The process id of the instance. */
  pid: number;
  /** When that process started, ISO 8601. Tells two processes with one pid apart. */
  startedAt: string;
  /** When the instance took the desk, ISO 8601. */
  openedAt: string;
};

/** The part of a `DeskOwner` that names a process. */
export type DeskInstance = { pid: number; startedAt: string };

/**
 * Something about the desk's files that the Space window's header shows.
 *
 * - `corrupt-file`: `file` could not be parsed. It was renamed to `setAsideAs`
 *   (`null` when the desk is not writable or the rename failed) and is treated as empty.
 * - `records-not-understood`: `count` entries of `file` do not have the shape
 *   this build knows. They are not used, and they are kept when the file is written.
 * - `stale-owner-replaced`: the owner file named a process that no longer runs.
 */
export type DeskNotice =
  | { kind: 'corrupt-file'; file: string; setAsideAs: string | null; at: string; message: string }
  | { kind: 'records-not-understood'; file: string; count: number; message: string }
  | { kind: 'stale-owner-replaced'; file: string; previous: DeskOwner; message: string };

/**
 * Why a desk operation failed.
 *
 * - `read-failed`, `write-failed`: the filesystem refused.
 * - `newer-version`: the file's `version` is higher than this build writes; it is left as it is.
 * - `not-writable`: another running instance owns the desk, so this one does not write.
 * - `not-owner`: the owner file no longer names this instance.
 * - `invalid-record`: the value to be written does not have the record's shape.
 * - `duplicate`: a record with the same identity is already there.
 * - `not-found`: the record to change is not there.
 */
export type DeskFailureKind =
  | 'read-failed'
  | 'write-failed'
  | 'newer-version'
  | 'not-writable'
  | 'not-owner'
  | 'invalid-record'
  | 'duplicate'
  | 'not-found';
